### ISSUE TITLE
Change format and behaviour of phonetic transcriptions without sound files 

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/Sound-Comparisons#351]
- [x] On all views, transcriptions without sound files should be shown in black font, not grey.  

- [x] Also, the script needs to interpret transcription entries that are "--" (two hyphens) or ".." (two dots) as meaning that there is and never will be any sound file for that word in that language.  So they should display only as a placeholder to show no transcription, perhaps "--" (two hyphens) itself.

**Comment by runjak** [comment]
Can you give me an example where to find current entries with `--` or `...` in them?

**Comment by PaulHeggarty** [comment]
I don’t think there are any (or perhaps a few in Romance), I had thought we would do it in the reverse order:  you get this ready, and then we apply it to the transcriptions.  If you want a test, I can send you an SQL with some examples.

**Comment by PaulHeggarty** [comment]
Here is an sql file with about ten words that now have .. (TWO dots, better in fact) as the transcription.  in this language: 
(http://www.soundcomparisons.com/#/en/Malakula/language/Taute%3A%20Alpalak)
Currently that page shows 'soon' as the transcription, but it should now show just -- (two hyphens).
In other words, convert the two dots to two hyphens, and display that.  Preferably without the enclosing [ ] brackets, to show that there's nothing phonetic, just no data.
[2016_05_18__Transcriptions_Malakula_215_-_Rgn_1_-_North_W-Nth.zip](https://github.com/lingdb/Sound-Comparisons/files/281504/2016_05_18__Transcriptions_Malakula_215_-_Rgn_1_-_North_W-Nth.zip)

**Comment by runjak** [comment]
Thanks - this should make it easier for me to get the desired results.

**Comment by runjak** [comment]
So I know where to look for such cases, I'm only a bit uncertain as to how you would like this to be displayed on the site.
The current way this would be displayed:
![screenshot_2016-05-25_14-43-55](https://cloud.githubusercontent.com/assets/5417642/15540386/52ccf20c-2287-11e6-915b-96370032cd75.png)
Possible alternatives:
![screenshot_2016-05-25_14-44-35](https://cloud.githubusercontent.com/assets/5417642/15540388/52dfc33c-2287-11e6-8aeb-2dd36725b29b.png)
![screenshot_2016-05-25_14-45-18](https://cloud.githubusercontent.com/assets/5417642/15540389/52ec24e2-2287-11e6-9f9b-527521f2a3c5.png)

**Comment by PaulHeggarty** [comment]
The first alternative is fine.
There are pros and cons of actually not even having these words showing for that language, but for now let's leave them showing.
One other consideration is what might affect the search/filter function on transcriptions.  Is there a way of telling it that these fields are to be completely ignored?  The reason is that some transcriptions will include hyphens and perhaps even dots, and/or they may have values in regular expressions.  We also don’t want them to be included in search results for ^$ or ., I suppose.

**Comment by runjak** [comment]
I've deployed the changes from this issue and think that they should work as intended.
It's possible that the usual caching problems apply.

**Comment by PaulHeggarty** [comment]
I actually put a confusing title on this issue, and there are two cases, one of which still remains.  This is that there are now lots of the Malakula transcriptions that are given as .. in the database.  On the map, the corresponding language dot appears, but without any transcription bubble.  This is fine.  On the table views, however, it would be nice to have the two dots showing, as per the second of Jakob's images above.
In fact, the cell appears but the two dots do not.  Could you put them in (I hope it won't be too complex to do this only in the tables, and not on the map.)
![screenshot - 27_05_2016 18_31_17](https://cloud.githubusercontent.com/assets/8819910/15614547/adf939a2-2439-11e6-8031-cada7db01bfe.png)

**Comment by PaulHeggarty** [comment]
I actually put a confusing title on this issue, and there are two cases, one of which still remains.  This is that there are now lots of the Malakula transcriptions that are given as .. in the database.  On the map, the corresponding language dot appears, but without any transcription bubble.  This is fine.  On the table views, however, it would be nice to have the two dots showing, as per the second of Jakob's images above.
In fact, the cell appears but the two dots do not.  Could you put them in (I hope it won't be too complex to do this only in the tables, and not on the map.)
![screenshot - 27_05_2016 18_31_17](https://cloud.githubusercontent.com/assets/8819910/15614547/adf939a2-2439-11e6-8031-cada7db01bfe.png)

**Comment by PaulHeggarty** [comment]
Sorry, I didn’t realise that I'd never actually hit the comment button on the above, so this issue is still actually live, albeit with only a very minor tweak left to fix.  Shame I didn’t realise this before you did the last deployment.

**Comment by PaulHeggarty** [comment]
Cells that are entirely blank in the 1 Word all Languages view (i.e. without any language, just the spare empty cells at the end of the last row in a language region group) nonetheless have the two dots showing, when they should be just blank.  
![screenshot - 15_06_2016 16_29_46](https://cloud.githubusercontent.com/assets/8819910/16083807/ae365eae-3316-11e6-8202-c009d38dfe76.png)
