### ISSUE TITLE
New permissions on SndCmp /sound directory prevent me from using it

### ISSUE THREAD

**Issue by Linguista** [lingdb/Sound-Comparisons#421]
Until very recently, I was able to create and delete arbitrary directories and files in `/srv/soundcomparisons/site/sound/`. That has now changed -- the new owner is `soundcomparisons`, and I have only read permissions.

This change prevents me from uploading, creating or deleting directories and files, which effectively brings my work to a screeching halt. (I need to delete folders and their contents when I make changes to transcriptions which have previously been uploaded, in order to make absolutely sure that the new ones match the sound files, and that no orphaned files stay on the server).

So I'd kindly request you address this issue in such a way as to allow me to continue to work as I had been until recently. Thanks!

**Comment by runjak** [comment]
Possible that I broke this when moving the `sound` folder on Tuesday.

**Comment by Linguista** [comment]
Could this be fixed by simply adding me to the `soundcomparisons` group?

**Comment by PaulHeggarty** [comment]
Comment to Scott:  rather than putting urgency notes in the issue title, please use the labels system to assign urgency level.  Please also use it to identify the type of issue, in this case a bug.

**Comment by Linguista** [comment]
Will do! Is `0th` the label for urgent matters?

**Comment by runjak** [comment]
On the server the group `soundcomparisons` is now defined like this:
```
soundcomparisons:x:1010:www-data,bibiko,runge,sadowsky,waegerle,heggarty
```
I've adjusted file permissions so that the sound directory may be modified by all members of the `soundcomparisons` group. I used these commands:
```shell
chmod -R soundcomparisons:soundcomparisons sound
cd sound
find -type d -exec chmod g+rwx {} \;
find -type f -exec chmod g=rw {} \;
```
With this the access problem should be fixed.

**Comment by Linguista** [comment]
I can confirm that the fix works for me. Thanks, Jakob!

**Comment by Linguista** [comment]
I'm afraid the permissions issues are not completely solved. I just uploaded/reuploaded 9 Mapudungun directories. The directories themselves inherited the following permissions:
`drwxrwxr-x   2 sadowsky         sadowsky`

The files they contain, meanwhile, inherited these permissions:
`-rw-rw-r--   1 sadowsky         sadowsky`

It's my understanding that both should belong to the `soundcomparisons` group. This does not seem to be causing any problems currently, but it's not inconceivable that a future change could have the unforeseen effect of breaking access to audio files.

**Comment by runjak** [comment]
Yes, I agree with your observation.
If I understand correctly `rsync` usually tries to match permissions with your local ones,
and thus will likely 'adjust' them on the server where possible.
I see two possible fixes for this:
1. If I'm not mistaken using ACLs it should be possible to force files created in a directory tree to inherit a certain group, but I'm not sure if this will work in all cases.
2. The easier but technically not as satisfying solution would be some kind of cron job or systemd timer that adjusts the file permissions every once in a while (hour or day should suffice).
